# Generated by Django 3.1.4 on 2021-06-29 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=datetime.datetime(2021, 6, 29, 16, 45, 8, 309555))),
                ('time', models.TimeField(blank=True, default=datetime.datetime(2021, 6, 29, 16, 45, 8, 309576))),
            ],
        ),
    ]
