# Generated by Django 3.1.4 on 2021-06-29 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentdates',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='assignmentdates',
            name='time',
            field=models.TimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
