# Generated by Django 3.1.4 on 2021-06-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customAdmin', '0002_auto_20210629_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdates',
            name='description',
            field=models.CharField(default='open', max_length=30),
        ),
    ]
