version: '3'

services:

 djangoapp:
  build: . 
  volumes:
   - .:/opt/services/djangoapp/src
   - static_volume:/opt/services/djangoapp/staticfiles

 web:
   build: .
   container_name: DJANGOXDOCKERNAME
   command: bash -c "guicorn hacking_challenge.wsgi -b 0.0.0.0:80"
   volumes:
     - .:/code
   command: python manage.py runserver 0.0.0.0:8000
   expose:
    - "80"
   ports:
     - "80:8000"

volumes:
   static_volume:
      driver: local
