version: '3'

services:


 web:
   build: .
   container_name: DJANGOXDOCKERNAME
   command: bash -c "uwsgi --socket hacking_challenge.sock --module hacking_challenge.wsgi --chmod-socket=666"
   volumes:
     - .:/code

volumes:
   static_volume:
      driver: local
