services:
 

 web:
   build: .
   environment:
     MYENV: EXAMPLE
   volumes:
     - .:/code
     - static-data:/static_files
 web_migrate:
   extends:
     service: web
   command: python manage.py migrate
 web_run:
   extends:
     service: web
   command: python manage.py runserver 0.0.0.0:8000
   ports:
     - "80:8000"
volumes:
   static-data:
      driver: local

