# Generated by Django 3.1.4 on 2021-06-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wolfIncorporated', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('loneWolfUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wolfIncorporated.lonewolfuser')),
            ],
        ),
    ]
