# Generated by Django 3.1.4 on 2021-06-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wolfIncorporated', '0003_fellowemployee_cookie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('sender', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='')),
                ('loneWolfUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wolfIncorporated.lonewolfuser')),
            ],
        ),
    ]
