# Generated by Django 3.1.4 on 2021-06-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfIncorporated', '0004_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='subjectLine',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
