# Generated by Django 3.1.4 on 2021-07-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wolfIncorporated', '0005_email_subjectline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lonewolfuser',
            old_name='admin',
            new_name='serverIsRunning',
        ),
    ]
