# Generated by Django 3.1.4 on 2021-07-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfIncorporated', '0006_auto_20210714_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lonewolfuser',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
