# Generated by Django 3.1.4 on 2021-06-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0004_auto_20210623_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='achievements',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
