# Generated by Django 3.1.4 on 2021-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0005_customuser_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='correctInARow',
            field=models.IntegerField(default=0),
        ),
    ]
