# Generated by Django 3.1.4 on 2021-06-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0006_customuser_correctinarow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='customText',
            field=models.TextField(blank=True, default=''),
        ),
    ]
