# Generated by Django 3.1.4 on 2021-07-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0008_auto_20210719_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completedAllChallenges',
            field=models.BooleanField(default=False),
        ),
    ]
