# Generated by Django 3.1.4 on 2021-07-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0009_customuser_completedallchallenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='numRequiredChallenges',
            field=models.IntegerField(default=0),
        ),
    ]
