# Generated by Django 3.1.4 on 2021-07-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0010_customuser_numrequiredchallenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='percentComplete',
            field=models.FloatField(default=0.0),
        ),
    ]
