# Generated by Django 3.2.3 on 2021-08-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0012_customuser_completedrequiredchallenges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='completedRequiredChallenges',
            field=models.IntegerField(default=1),
        ),
    ]
