# Generated by Django 3.2.3 on 2021-12-28 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginSignup', '0014_alter_customuser_completedrequiredchallenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='completedAllRequired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hasYouOkayBro',
            field=models.BooleanField(default=False),
        ),
    ]
