# Generated by Django 3.1.4 on 2021-06-10 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=50)),
                ('title', models.CharField(default='Level', max_length=20)),
                ('description', models.CharField(default='A very nice description', max_length=300)),
                ('order', models.IntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('pointValue', models.IntegerField(default=10)),
                ('optionalChallenge', models.BooleanField(default=False)),
                ('difficultyIndicator', models.CharField(default='Easy', max_length=20)),
                ('challengeSeries', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint', models.TextField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge')),
            ],
        ),
    ]
