# Generated by Django 3.2.3 on 2021-05-20 18:42

from django.db import migrations


def populate_db(apps, schema_editor):
    Challenge = apps.get_model('challenges', 'Challenge')
    Hint = apps.get_model('challenges', 'Hint')

    # This flag cannot change or it will break
    challenge_1 = Challenge(flag="password", title="Level 1", order=1, templateValue=0,
                            hidden=False, description="You dare try to hack me!? You will never be able to!")
    challenge_1.save()

    hint_1_0 = Hint(challenge=challenge_1, hint="HTML")
    hint_1_0.save()

    hint_1_1 = Hint(challenge=challenge_1, hint="Browser Developer Tools")
    hint_1_1.save()

    # ok to change
    challenge_2 = Challenge(flag="FBJKLDAS$@*()789fds", title="Level 2", order=2, hidden=False,
                            description="I admit, that first one was terrible security. This one isn't nearly as terrible.", templateValue=1)
    challenge_2.save()

    hint_2_0 = Hint(challenge=challenge_2, hint="HTML")
    hint_2_0.save()

    hint_2_1 = Hint(challenge=challenge_2, hint="Browser Developer Tools")
    hint_2_1.save()

    # This flag cannot change, it will break (uses a JS function to generate)
    challenge_3 = Challenge(flag="0iL2oV4eH6aC8kI10nG", title="Level 3", order=3, hidden=False,
                            description="HA! Javascript will help me here! Good luck with this one, little pest!", templateValue=2)
    challenge_3.save()

    hint_3_0 = Hint(challenge=challenge_3, hint="HTML")
    hint_3_0.save()

    hint_3_0 = Hint(challenge=challenge_3, hint="Javascript Functions")
    hint_3_0.save()

    hint_3_0 = Hint(challenge=challenge_3, hint="Browser Developer Tools")
    hint_3_0.save()

    # ok to change
    challenge_4 = Challenge(flag="@UK#Kb3ir3i2dsa", title="Level 4", order=4, hidden=False,
                            description="Fine. Fine. Fine. I get it. Keeping it offsite would be a much better idea they told me. I'll do that.", templateValue=3)
    challenge_4.save()

    hint_4_0 = Hint(challenge=challenge_4, hint="HTTP Request Headers")
    hint_4_0.save()

    # ok to change
    challenge_5 = Challenge(flag="T/E))2n-_-0b!cj4--H*0?", title="Level 5", order=5, hidden=False,
                            description="Do you not know who I am!? Leave me and my site alone! Offsite obviously didn't work. I'm using Javascript again.", templateValue=4)
    challenge_5.save()

    hint_5_0 = Hint(challenge=challenge_5, hint="Developer Tools")
    hint_5_0.save()

    # This flag cannot change, it is reliant upon a JS function
    challenge_6 = Challenge(flag="D0gI2qF4aO6", title="Level 6", order=6, hidden=False,
                            description="I guess I underestimated just who YOU were. You ever think what would happen if I were hacking you at the same time? Maybe I'm scanning your IP address right now to find out where you live. Mwahaha. Anyways, I moved the password out of the HTML, sending it directly from the server instead. Good luck finding it now LOL.", templateValue=5)
    challenge_6.save()

    hint_6_0 = Hint(challenge=challenge_6, hint="HTML")
    hint_6_0.save()

    hint_6_1 = Hint(challenge=challenge_6, hint="Javascript Functions")
    hint_6_1.save()

    hint_6_2 = Hint(challenge=challenge_6, hint="Browser Developer Tools")
    hint_6_2.save()

    hint_6_3 = Hint(challenge=challenge_6, hint="HTML Forms")
    hint_6_3.save()

    hint_6_4 = Hint(challenge=challenge_6, hint="Website URL Routing")
    hint_6_4.save()

    # ok to change
    challenge_7 = Challenge(flag="@U/*Db4(DV}wT{F`e", title="Level 7", order=7, hidden=False,
                            description="Forgive me if I seem neglectful now. I have... other tasks at hand. I just quickly implemented a sign in form instead. Sign in, gives password. Seems a little redundant for me to remember a password but oh well.", templateValue=6)
    challenge_7.save()

    hint_7_0 = Hint(challenge=challenge_7, hint="HTML")
    hint_7_0.save()

    hint_7_1 = Hint(challenge=challenge_7, hint="Javascript Functions")
    hint_7_1.save()

    hint_7_2 = Hint(challenge=challenge_7, hint="Browser Developer Tools")
    hint_7_2.save()

    hint_7_3 = Hint(challenge=challenge_7, hint="HTML Forms")
    hint_7_3.save()

    hint_7_3 = Hint(challenge=challenge_7, hint="GET/POST Request/Response")
    hint_7_3.save()

    # ok to change
    challenge_8 = Challenge(flag="/D3<]3v3b4Q3H,tDn", title="Level 8", order=8, hidden=False,
                            description="Hmmm... I think you could actually be handy to me. Use White Box and find the flags and submit them to me. Thank you kindly.", templateValue=7)
    challenge_8.save()

    hint_8_0 = Hint(challenge=challenge_8, hint="HTML")
    hint_8_0.save()

    hint_8_1 = Hint(challenge=challenge_8, hint="Javascript Functions")
    hint_8_1.save()

    hint_8_2 = Hint(challenge=challenge_8, hint="Browser Developer Tools")
    hint_8_2.save()

    hint_8_3 = Hint(challenge=challenge_8, hint="HTML Forms")
    hint_8_3.save()

    hint_8_4 = Hint(challenge=challenge_8, hint="GET/POST Request/Response")
    hint_8_4.save()

    hint_8_5 = Hint(challenge=challenge_8, hint="Unsanitized input")
    hint_8_5.save()

    hint_8_6 = Hint(challenge=challenge_8,
                    hint="Unix list and read commands... meow")
    hint_8_6.save()

    hint_8_7 = Hint(challenge=challenge_8, hint="Hidden Files")
    hint_8_7.save()

    # ok to change
    challenge_9 = Challenge(flag="1a2s3d4f5bg6h7j8k9l", title="Level 9", order=9, hidden=False,
                            description="Good. Good. There are more security flaws. Find them.", templateValue=8)
    challenge_9.save()

    hint_9_0 = Hint(challenge=challenge_9, hint="HTML")
    hint_9_0.save()

    hint_9_1 = Hint(challenge=challenge_9, hint="Javascript Functions")
    hint_9_1.save()

    hint_9_2 = Hint(challenge=challenge_9, hint="Browser Developer Tools")
    hint_9_2.save()

    hint_9_3 = Hint(challenge=challenge_9, hint="HTML Forms")
    hint_9_3.save()

    hint_9_4 = Hint(challenge=challenge_9, hint="GET/POST Request/Response")
    hint_9_4.save()

    hint_9_5 = Hint(challenge=challenge_9, hint="Unsanitized input")
    hint_9_5.save()

    hint_9_6 = Hint(challenge=challenge_9,
                    hint="Unix list and read commands... meow")
    hint_9_6.save()

    hint_9_7 = Hint(challenge=challenge_9, hint="Hidden Files")
    hint_9_7.save()

    # Ok to change
    challenge_20 = Challenge(flag="er4bw{^a=Z,dGeyF=", title="Level 20", order=10, hidden=False,
                             description="You have potential, kid. Imma let you in on a little secret.", difficultyIndicator="Moderate", templateValue=9)
    challenge_20.save()

    hint_20_0 = Hint(challenge=challenge_20, hint="HTML")
    hint_20_0.save()

    hint_20_1 = Hint(challenge=challenge_20, hint="Javascript Functions")
    hint_20_1.save()

    hint_20_2 = Hint(challenge=challenge_20, hint="Browser Developer Tools")
    hint_20_2.save()

    hint_20_3 = Hint(challenge=challenge_20, hint="HTML Forms")
    hint_20_3.save()

    hint_20_4 = Hint(challenge=challenge_20, hint="GET/POST Request/Response")
    hint_20_4.save()

    hint_20_5 = Hint(challenge=challenge_20, hint="Unsanitized input")
    hint_20_5.save()

    hint_20_6 = Hint(challenge=challenge_20,
                     hint="Unix list and read commands... meow")
    hint_20_6.save()

    hint_20_7 = Hint(challenge=challenge_20, hint="Hidden Files")
    hint_20_7.save()

    hint_20_8 = Hint(challenge=challenge_20, hint="Cookies")
    hint_20_8.save()

    hint_20_9 = Hint(challenge=challenge_20,
                     hint="The Cookie's path is significant, too")
    hint_20_9.save()

    # ok to change
    challenge_21 = Challenge(flag="RARW10101b0RKDFJLS", title="Level 21", order=11, hidden=False,
                             description="They think themselves so safe. Could you kindly get an admin's email and password for me?", difficultyIndicator="Moderate", templateValue=10)
    challenge_21.save()

    hint_21_0 = Hint(challenge=challenge_21, hint="Brute Force Attacks")
    hint_21_0.save()

    hint_21_1 = Hint(challenge=challenge_21,
                     hint="Fetch Commands in Javascript")
    hint_21_1.save()

    hint_21_2 = Hint(challenge=challenge_21,
                     hint="Don't mess with the request headers the browser uses")
    hint_21_2.save()

    # ok to change
    challenge_22 = Challenge(flag="mYCaBbageS!", title="Brute Force Part 2", description="Contained in a previous challenge were more emails and passwords. Find the correct one and log in. This is the easiest of the hard challenges",
                             order=15, difficultyIndicator="l33t", optionalChallenge=True, templateValue=11)
    challenge_22.save()

    hint_22_0 = Hint(challenge=challenge_22, hint="Brute Force Methods")
    hint_22_0.save()

    # ok to change, this is found by db
    challenge_23 = Challenge(flag="YouAreAnAdminNow77@^</>", title="Cross Site Scripting", description="We need you to find a way to become an admin for the very man you were working for and end him. He is evil. You helped him. Our intel tells us there is a single way for this to be done. Good luck.",
                             order=16, difficultyIndicator="l33t", templateValue=12, optionalChallenge=True)
    challenge_23.save()

    hint_23_0 = Hint(challenge=challenge_23,
                     hint="Take a look at the settings page")
    hint_23_0.save()

    hint_23_1 = Hint(challenge=challenge_23,
                     hint="Find a way to make yourself an admin... Maybe Cross Site Scripting or Get Requests?")
    hint_23_1.save()

    # do not change, this is the encryption one
    challenge_24 = Challenge(
        flag="youhavedonewelltofindthekey",
        title="Cryptology Challenge", 
        description="A flag for the challenge has been recieved, what could we do with it?",
        order=17,
        difficultyIndicator="l33t",
        optionalChallenge=True,
        templateValue=13
    )

    # challenge_24 = Challenge(flag="congratulationsondecryptingthis!", title="Cryptology Challenge",
                            #  description="Below is a paragraph that has been encrypted. Solve it", order=17, difficultyIndicator="l33t", optionalChallenge=True, templateValue=13)
    challenge_24.save()

    hint_24_0 = Hint(challenge=challenge_24, hint="Code Breaking Skills")
    hint_24_0.save()

    hint_24_1 = Hint(challenge=challenge_24, hint="Tenacity.")
    hint_24_1.save()

    hint_24_2 = Hint(challenge=challenge_24,
                     hint="What are some forms of encryption? I'm sure you can get over this hill")
    hint_24_2.save()

    hint_24_3 = Hint(challenge=challenge_24, hint="The final flag is a string of words, so you will know that you've found it when you do! (Although there aren't spaces)")
    hint_24_3.save()

    # In file, /wolfIncorporated/templates/wolfIncorporated/homepage.html
    challenge_loneWolf_0 = Challenge(flag="#CH**O#SEN_#^%ON--=E", title="Lone Wolf Part 1", description="Your challenge is to break into a website called Lone Wolf (link down below) and shut it down. End their company for me.",
                                     order=12, difficultyIndicator="Hard", challengeSeries="LoneWolf", templateValue=14, optionalChallenge=True)
    challenge_loneWolf_0.save()

    hint_loneWolf_0 = Hint(challenge=challenge_loneWolf_0, hint="GET requests")
    hint_loneWolf_0.save()

    hint_loneWolf_0_1 = Hint(
        challenge=challenge_loneWolf_0, hint="Weak Authentication validators")
    hint_loneWolf_0_1.save()

    # ok to change
    challenge_loneWolf_2 = Challenge(flag="DO!ITSTRI#^KETH445ESE*RV^ERD#@OWN", title="Lone Wolf Part 2", description="Your challenge is to break into a website called Lone Wolf (link down below) and shut it down. End their company for me.",
                                     order=13, difficultyIndicator="Hard", challengeSeries="LoneWolf", templateValue=16, optionalChallenge=True)
    challenge_loneWolf_2.save()

    hint_loneWolf_0_2 = Hint(
        challenge=challenge_loneWolf_2, hint="Fetch Requests")
    hint_loneWolf_0_2.save()

    hint_loneWolf_0_3 = Hint(
        challenge=challenge_loneWolf_2, hint="Maybe try using the console?")
    hint_loneWolf_0_3.save()

    # ok to change
    challenge_loneWolf_3 = Challenge(flag="Y2OU!@MONSdsTER%^", title="Lone Wolf Part 3", description="Your challenge is to break into a website called Lone Wolf (link down below) and shut it down. End their company for me.",
                                     order=14, difficultyIndicator="Hard", challengeSeries="LoneWolf", templateValue=17, optionalChallenge=True)
    challenge_loneWolf_3.save()


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
