# Generated by Django 3.1.4 on 2021-06-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_populateChallenges'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['order']},
        ),
    ]
