# Generated by Django 3.2.3 on 2021-06-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='challengeSeries',
            field=models.CharField(default='Basic', max_length=50),
        ),
    ]
