# Generated by Django 3.1.4 on 2021-07-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='numberOfUsersOnThisChallenge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='totalIncorrectGuesses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challengeSeries',
            field=models.CharField(default='Basic', max_length=50),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='templateValue',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='title',
            field=models.CharField(default='Challenge', max_length=20),
        ),
    ]
