# Generated by Django 3.1.4 on 2021-06-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_challenge_challengeseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='numberOfUsersOnThisChallenge',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='challenge',
            name='totalIncorrectGuesses',
            field=models.IntegerField(default=0),
        ),
    ]
