# Generated by Django 3.1.4 on 2021-05-20 15:50

from django.db import migrations
from django.utils import timezone


def populate_db(apps, schema_editor):
    Testing = apps.get_model('playground', 'Testing')

    test1 = Testing(description="This is a test from the database!", date=timezone.now(), completed=False)
    test1.save()



class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)

            ]
